### ISSUE TITLE
Merging of the PR

### ISSUE THREAD

**Issue by zarry** [chef-brigade/mongodb-cookbook#37]
@luishdez  You seem to be driving the train at the moment in regards to the open PRs.  I haven't had a ton of time lately so the effort is appreciated.  

I am starting to free up a little and can lend some time.  I am giving a second eye on some of these PR's you have reviewed and tagged, my question is after I look over them and think they are good do you want me to proceed with merge?  Are you covering the merges working out a proper order so they can be merged smoothly?  

Just wanted to get this sorted out so we aren't stepping on each other.

**Comment by luishdez** [comment]
Sure!! That's awesome. Next week I'll be traveling so it will keep things moving. Go ahead.

My strategy so far is: 

1. locate easy merges: https://github.com/chef-brigade/mongodb-cookbook/labels/merge%3A%20easy
I think you can merge all of them without following any order because they won't conflict. ( I can't assure you 100% ) But these PRs are small and easy to manage.

2. The rest of PRs are tagged with `merge: complex` and `comp: replicaset` most of them modify a lot of core features and multiple files per PR… mainly the replicaset feature. 

Trying to merge those prs it will be too complex. I would do is drop all of them and work in a new branch `feature/lwrp` once is complete work on `feature/replicaset` … But taking the ideas/code from those closed PRs. Imho it will be easy to work in a clean slate.

**Comment by luishdez** [comment]
Closing this to keep it clean :)
